// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTest(arg1:string):Promise<boolean>;

export function GetTests():Promise<Array<string>>;
