// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<backend.LoginResponse>;
