// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function GetUsers() {
  return window['go']['backend']['App']['GetUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}
