// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTest(arg1) {
  return window['go']['backend']['App']['AddTest'](arg1);
}

export function GetTests() {
  return window['go']['backend']['App']['GetTests']();
}
