CREATE TABLE IF NOT EXISTS users(
  id INTEGER PRIMARY KEY AUTOINCREAMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash BLOB NOT NULL,
  isAdmin BOOL DEFAULT FALSE,
  created_at TEXT DEFAULT (datetime('now'))
)
