const dummyData = [
  {
    id: 1012,
    name: "Paracetamol",
    manufacture: "GSK",
    expiry: "2025-11-01",
    price: "2.50",
    amount: 100,
    active: true,
    type: "pill",
  },
  {
    id: 8493,
    name: "Amoxicillin",
    manufacture: "Pfizer",
    expiry: "2026-01-15",
    price: "5.00",
    amount: 60,
    active: true,
    type: "capsule",
  },
  {
    id: 6542,
    name: "Cetirizine",
    manufacture: "Sun Pharma",
    expiry: "2025-08-10",
    price: "1.80",
    amount: 150,
    active: true,
    type: "pill",
  },
  {
    id: 7820,
    name: "Ibuprofen",
    manufacture: "Bayer",
    expiry: "2026-02-01",
    price: "3.25",
    amount: 80,
    active: true,
    type: "pill",
  },
  {
    id: 2156,
    name: "Dextromethorphan",
    manufacture: "Novartis",
    expiry: "2024-07-20",
    price: "4.10",
    amount: 30,
    active: false,
    type: "syrup",
  },
  {
    id: 9381,
    name: "Hydrocortisone Cream",
    manufacture: "Cipla",
    expiry: "2025-05-12",
    price: "3.99",
    amount: 50,
    active: true,
    type: "cream",
  },
  {
    id: 3774,
    name: "Aspirin",
    manufacture: "Johnson & Johnson",
    expiry: "2026-03-01",
    price: "2.75",
    amount: 200,
    active: true,
    type: "pill",
  },
  {
    id: 4952,
    name: "Metformin",
    manufacture: "Abbott",
    expiry: "2025-10-25",
    price: "6.50",
    amount: 120,
    active: true,
    type: "pill",
  },
  {
    id: 6701,
    name: "Salbutamol Inhaler",
    manufacture: "GSK",
    expiry: "2025-01-10",
    price: "8.00",
    amount: 40,
    active: true,
    type: "inhaler",
  },
  {
    id: 2239,
    name: "Loratadine",
    manufacture: "Zydus",
    expiry: "2025-06-30",
    price: "2.30",
    amount: 90,
    active: true,
    type: "pill",
  },
  {
    id: 3010,
    name: "Omeprazole",
    manufacture: "Teva",
    expiry: "2025-09-05",
    price: "5.20",
    amount: 100,
    active: true,
    type: "capsule",
  },
  {
    id: 1928,
    name: "Azithromycin",
    manufacture: "Sandoz",
    expiry: "2025-11-17",
    price: "4.75",
    amount: 70,
    active: false,
    type: "pill",
  },
  {
    id: 6129,
    name: "Chlorpheniramine",
    manufacture: "Glenmark",
    expiry: "2026-03-10",
    price: "1.99",
    amount: 60,
    active: true,
    type: "syrup",
  },
  {
    id: 8305,
    name: "Ciprofloxacin",
    manufacture: "Dr. Reddy's",
    expiry: "2025-07-25",
    price: "3.85",
    amount: 40,
    active: true,
    type: "pill",
  },
  {
    id: 5466,
    name: "Clotrimazole",
    manufacture: "Bausch Health",
    expiry: "2026-04-11",
    price: "2.60",
    amount: 25,
    active: true,
    type: "cream",
  },
  {
    id: 1078,
    name: "Diclofenac",
    manufacture: "Ranbaxy",
    expiry: "2026-05-02",
    price: "2.95",
    amount: 90,
    active: true,
    type: "gel",
  },
  {
    id: 4651,
    name: "Doxycycline",
    manufacture: "Mylan",
    expiry: "2025-08-12",
    price: "4.40",
    amount: 80,
    active: true,
    type: "capsule",
  },
  {
    id: 3542,
    name: "Insulin",
    manufacture: "Novo Nordisk",
    expiry: "2024-12-01",
    price: "15.00",
    amount: 20,
    active: true,
    type: "injection",
  },
  {
    id: 9783,
    name: "Lisinopril",
    manufacture: "Lupin",
    expiry: "2026-02-01",
    price: "6.70",
    amount: 100,
    active: true,
    type: "pill",
  },
  {
    id: 5123,
    name: "Montelukast",
    manufacture: "Torrent",
    expiry: "2025-11-11",
    price: "3.40",
    amount: 75,
    active: true,
    type: "pill",
  },
  {
    id: 2831,
    name: "Nystatin",
    manufacture: "Aurobindo",
    expiry: "2025-06-06",
    price: "2.15",
    amount: 30,
    active: true,
    type: "suspension",
  },
  {
    id: 6643,
    name: "Pantoprazole",
    manufacture: "Cadila Healthcare",
    expiry: "2025-10-10",
    price: "5.90",
    amount: 60,
    active: true,
    type: "pill",
  },
  {
    id: 8011,
    name: "Prednisone",
    manufacture: "Zydus",
    expiry: "2026-01-20",
    price: "4.85",
    amount: 55,
    active: true,
    type: "pill",
  },
  {
    id: 2244,
    name: "Ranitidine",
    manufacture: "Apotex",
    expiry: "2025-12-12",
    price: "2.10",
    amount: 100,
    active: false,
    type: "pill",
  },
  {
    id: 3560,
    name: "Simvastatin",
    manufacture: "AstraZeneca",
    expiry: "2026-04-14",
    price: "6.25",
    amount: 100,
    active: true,
    type: "pill",
  },
  {
    id: 9350,
    name: "Tetracycline",
    manufacture: "Sun Pharma",
    expiry: "2025-09-09",
    price: "3.75",
    amount: 40,
    active: true,
    type: "capsule",
  },
  {
    id: 1476,
    name: "Timolol",
    manufacture: "Allergan",
    expiry: "2025-07-01",
    price: "7.40",
    amount: 25,
    active: true,
    type: "eye drops",
  },
  {
    id: 7592,
    name: "Tramadol",
    manufacture: "Cipla",
    expiry: "2026-02-28",
    price: "5.99",
    amount: 60,
    active: true,
    type: "capsule",
  },
  {
    id: 2019,
    name: "Warfarin",
    manufacture: "Pfizer",
    expiry: "2026-03-03",
    price: "4.10",
    amount: 70,
    active: true,
    type: "pill",
  },
  {
    id: 4884,
    name: "Zolpidem",
    manufacture: "Sanofi",
    expiry: "2025-08-30",
    price: "6.90",
    amount: 30,
    active: true,
    type: "pill",
  },
  {
    id: 6315,
    name: "Vitamin C",
    manufacture: "GNC",
    expiry: "2026-05-05",
    price: "3.00",
    amount: 200,
    active: true,
    type: "tablet",
  },
  {
    id: 2047,
    name: "Ferrous Sulfate",
    manufacture: "Nature Made",
    expiry: "2026-06-30",
    price: "2.70",
    amount: 100,
    active: true,
    type: "pill",
  },
  {
    id: 7268,
    name: "Folic Acid",
    manufacture: "Now Foods",
    expiry: "2025-09-01",
    price: "1.90",
    amount: 100,
    active: true,
    type: "tablet",
  },
  {
    id: 3391,
    name: "Calcium Carbonate",
    manufacture: "Caltrate",
    expiry: "2025-10-10",
    price: "2.25",
    amount: 150,
    active: true,
    type: "tablet",
  },
  {
    id: 1425,
    name: "Magnesium Citrate",
    manufacture: "Rexall",
    expiry: "2026-01-01",
    price: "3.45",
    amount: 90,
    active: true,
    type: "liquid",
  },
  {
    id: 6753,
    name: "Multivitamin",
    manufacture: "Centrum",
    expiry: "2026-02-20",
    price: "4.99",
    amount: 300,
    active: true,
    type: "tablet",
  },
  {
    id: 5579,
    name: "Iron Supplement",
    manufacture: "Nature’s Bounty",
    expiry: "2025-08-15",
    price: "2.95",
    amount: 120,
    active: true,
    type: "tablet",
  },
  {
    id: 3498,
    name: "Zinc Gluconate",
    manufacture: "Solgar",
    expiry: "2025-12-01",
    price: "3.80",
    amount: 100,
    active: true,
    type: "tablet",
  },
  {
    id: 1140,
    name: "Lactulose",
    manufacture: "Abbott",
    expiry: "2026-03-10",
    price: "6.10",
    amount: 40,
    active: true,
    type: "syrup",
  },
  {
    id: 8890,
    name: "Budesonide Nasal Spray",
    manufacture: "Mylan",
    expiry: "2025-10-20",
    price: "5.50",
    amount: 35,
    active: true,
    type: "spray",
  },
  {
    id: 3294,
    name: "Betadine",
    manufacture: "Purdue Pharma",
    expiry: "2025-06-18",
    price: "3.35",
    amount: 45,
    active: true,
    type: "solution",
  },
  {
    id: 4132,
    name: "Antacid Gel",
    manufacture: "Gelusil",
    expiry: "2025-07-30",
    price: "4.20",
    amount: 80,
    active: true,
    type: "gel",
  },
  {
    id: 5778,
    name: "Cough Drops",
    manufacture: "Halls",
    expiry: "2026-01-25",
    price: "1.50",
    amount: 150,
    active: true,
    type: "lozenge",
  },
  {
    id: 2467,
    name: "Throat Spray",
    manufacture: "Chloraseptic",
    expiry: "2025-09-11",
    price: "3.60",
    amount: 20,
    active: true,
    type: "spray",
  },
  {
    id: 1093,
    name: "Eye Lubricant",
    manufacture: "Refresh",
    expiry: "2026-02-10",
    price: "7.00",
    amount: 30,
    active: true,
    type: "eye drops",
  },
  {
    id: 9834,
    name: "Nasal Decongestant",
    manufacture: "Vicks",
    expiry: "2025-08-01",
    price: "4.70",
    amount: 50,
    active: true,
    type: "spray",
  },
  {
    id: 4927,
    name: "Topical Antifungal",
    manufacture: "Tinactin",
    expiry: "2025-11-25",
    price: "5.10",
    amount: 20,
    active: true,
    type: "cream",
  },
  {
    id: 3654,
    name: "Pain Relief Patch",
    manufacture: "Salonpas",
    expiry: "2026-04-04",
    price: "6.30",
    amount: 10,
    active: true,
    type: "patch",
  },
];
export default dummyData;
